version: "3.7"
services:
  database-mysql:
    image: postgres
    restart: always
    environment:
      # POSTGRES_HOST: localhost
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:5432"
    expose:
      - 3307
    volumes:
      - ./mysql-data:/var/lib/mysql
  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    volumes:
      - ./mysql-data:/var/lib/mysql
volumes:
  mysql-data:
