version: "3.1"
services:
  database-mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      default-authentication-plugin: mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
