version: "3.7"
services:
  database-mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_HOST: localhost
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    expose:
      - 3307
    volumes:
      - ./mysql-data:/var/lib/mysql
  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: database-mysql
    ports:
      - "8081:8080"
    volumes:
      - ./mysql-data:/var/lib/mysql
volumes:
  mysql-data:
